[package]
name = "redis_streams"
version = "0.1.0"
authors = ["grippy <gmelton@gmail.com>"]
edition = "2018"

[dependencies]
# redis = {git = "https://github.com/mitsuhiko/redis-rs.git"}
redis = "0.11.0"

[dev-dependencies]
rand = "0.6"
net2 = "0.2"
futures = "0.1"
